export default [
  {
    id: 1,
    title: "CEDIRATES",
    description: "Compare Exchange Rates and Fuel Prices",
    logo: "/images/cedi.png",
    skills: ["NEXT", "TAILWIND", "EXPRESS", "NODEJS", "MONGODB"],
    website: "https://cedirates.com/",
    github: "https://github.com/eakelvin",
    status: "true",
  },
  {
    id: 3,
    title: "VILLAGE CREATORS",
    description:
      "Celebrate creativity, nurture growth, build community connections",
    logo: "/images/vc.png",
    skills: ["NEXT", "BOOTSTRAP", "SANITY"],
    website: "https://www.villagecreators.net/",
    github: "https://github.com/eakelvin/village-creators-main.git",
    status: "true",
  },
  {
    id: 2,
    title: "EDFRICA",
    description: "Educative Management System",
    logo: "/images/edfrica.jpg",
    skills: ["REACT", "MUI", ""],
    website: "https://www.edfrica.com/",
    // website: "https://app.edfrica.com/",
    github: "https://github.com/eakelvin",
    status: "true",
  },
  {
    id: 4,
    title: "MAVE SPORTS",
    description: "News/Blog - Football and Basketball content",
    logo: "/images/mave1.jpg",
    skills: ["WORDPRESS"],
    website: "https://mavesportsnetwork.com/",
    status: "true",
  },
  {
    id: 5,
    title: "DEV JOBS",
    description: "A webapp to help users search for jobs",
    logo: "/images/dev.jpg",
    skills: ["REACT", "BOOTSTRAP"],
    website: "https://devjobs-ea.netlify.app/",
    github: "https://github.com/eakelvin/DevJobs-Project.git",
    status: "false",
  },
  {
    id: 8,
    title: "EA TOUR",
    description: "Explore and discover the best tourism content in Ghana",
    logo: "/images/tour.jpg",
    skills: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP"],
    website: "https://tour-ea.netlify.app/",
    github: "https://github.com/eakelvin/EA-Tour.git",
    status: "false",
  },
  {
    id: 13,
    title: "COUNTRY APP",
    description:
      "A website that contains details of all countries in the world",
    logo: "/images/country-app.jpg",
    skills: ["API", "TAILWIND CSS", "REACT"],
    website: "https://countries-app-ea.netlify.app/",
    github: "https://github.com/eakelvin/countries-app.git",
    status: "false",
  },
  {
    id: 15,
    title: "TENZIES GAME",
    description: "Play a game of rolling dice until all the dice are the same",
    logo: "/images/tenzies.jpeg",
    skills: ["REACT", "CSS"],
    website: "https://tenzies-game-ea.netlify.app/",
    github: "https://github.com/eakelvin/tenzies-game.git",
    status: "false",
  },
  {
    id: 9,
    title: "API PROJECTS",
    description: "A collection of different web apps that utilize APIs",
    logo: "/images/API.jpg",
    skills: ["HTML", "VANILLA CSS", "JAVASCRIPT", "REST API"],
    website: "https://api-app-ea.netlify.app/",
    github: "https://github.com/eakelvin/Api-projects.git",
    status: "false",
  },
  {
    id: 19,
    title: "SPIN THE BOTTLE GAME",
    description: "Spin the bottle to generate a random dare",
    logo: "/images/spin.jpeg",
    skills: ["TAILWIND CSS", "JAVASCRIPT", "REST API"],
    website: "https://spinthebottleklm.netlify.app/",
    github: "https://github.com/blameleo/spin-the-bottle.git",
    status: "false",
  },
  // {
  //   "id": 20,
  //   "title": "",
  //   "description": "",
  //   "logo": "/images/",
  //   "skills": ["REACT", "CSS"],
  //   "website": "",
  //   "github": "",
  // },
];
