export default [
  {
    id: 1,
    title: "CEDIRATES",
    description: "Compare Exchange Rates and Fuel Prices",
    logo: ["/images/cedi.png", "/images/cedi2.png"],
    skills: ["NEXT", "TAILWIND", "EXPRESS", "NODEJS", "MONGODB"],
    website: "https://cedirates.com/",
    github: "https://github.com/eakelvin",
    status: "true",
  },
  {
    id: 2,
    title: "VILLAGE CREATORS",
    description:
      "Celebrate creativity, nurture growth, build community connections",
    logo: ["/images/vc.png", "/images/vc2.png"],
    skills: ["NEXT", "BOOTSTRAP", "SANITY"],
    website: "https://www.villagecreators.net/",
    github: "https://github.com/eakelvin/village-creators-main.git",
    status: "true",
  },
  {
    id: 3,
    title: "EDFRICA",
    description: "Educative Management System",
    logo: ["/images/edfrica.jpg", "/images/edfrica2.jpg"],
    skills: ["REACT", "MUI", ""],
    website: "https://www.edfrica.com/",
    // website: "https://app.edfrica.com/",
    github: "https://github.com/eakelvin",
    status: "true",
  },
  {
    id: 4,
    title: "MAVE SPORTS",
    description: "News/Blog - Football and Basketball content",
    logo: ["/images/mave1.jpg", "/images/mave2.jpg"],
    skills: ["WORDPRESS"],
    website: "https://mavesportsnetwork.com/",
    status: "true",
  },
  {
    id: 5,
    title: "DEV JOBS",
    description: "A webapp to help users search for jobs",
    logo: ["/images/dev.jpg", "/images/dev2.jpg"],
    skills: ["REACT", "BOOTSTRAP"],
    website: "https://devjobs-ea.netlify.app/",
    github: "https://github.com/eakelvin/DevJobs-Project.git",
    status: "false",
  },
  {
    id: 6,
    title: "EA TOUR",
    description: "Explore and discover the best tourism content in Ghana",
    logo: ["/images/tour.jpg", "/images/tour2.jpg"],
    skills: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP"],
    website: "https://tour-ea.netlify.app/",
    github: "https://github.com/eakelvin/EA-Tour.git",
    status: "false",
  },
  {
    id: 7,
    title: "COUNTRY APP",
    description:
      "A website that contains details of all countries in the world",
    logo: ["/images/country-app.jpg", "/images/country-app2.jpg"],
    skills: ["API", "TAILWIND CSS", "REACT"],
    website: "https://countries-app-ea.netlify.app/",
    github: "https://github.com/eakelvin/countries-app.git",
    status: "false",
  },
  {
    id: 8,
    title: "API PROJECTS",
    description: "A collection of different web apps that utilize APIs",
    logo: ["/images/API.jpg", "/images/API2.jpg"],
    skills: ["HTML", "VANILLA CSS", "JAVASCRIPT", "REST API"],
    website: "https://api-app-ea.netlify.app/",
    github: "https://github.com/eakelvin/Api-projects.git",
    status: "false",
  },

  // {
  //   "id": 20,
  //   "title": "",
  //   "description": "",
  //   "logo": "/images/",
  //   "skills": ["REACT", "CSS"],
  //   "website": "",
  //   "github": "",
  // },
];
